[mcp_servers.codebase-memory-mcp]
command = "codebase-memory-mcp"
args = []
id = ""

[mcp_servers.context7]
command = "npx"
args = [ "-y", "@upstash/context7-mcp",]
id = ""

[mcp_servers.mcp-package-version]
command = "npx"
args = [ "-y", "mcp-package-version",]
id = ""

[mcp_servers.repomix]
command = "npx"
args = [ "-y", "repomix", "--mcp",]
id = ""

[mcp_servers.codebase-memory-mcp.env]

[mcp_servers.context7.env]

[mcp_servers.mcp-package-version.env]

[mcp_servers.repomix.env]
