/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Returns the kernel version, reached through the Rust consumer surface.
 *
 * Placeholder so the addon exports something callable from JavaScript and so the
 * dependency edges onto `prompting-press`/`prompting-press-core` are exercised.
 */
export declare function coreVersion(): string
